apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nodejs-kdhibrqn
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/nodejs-kdhibrqn:72a888d41029281a4e8ff2667b0af57103c4746a@sha256:9975f7f291f2297ababa91d241b8382ac191208c49564d63645525644ea3b5c3
          name: container-image
